Repository commercelayer/app-elements, pull requests merged in 2023-11, with the labels that each got.

#409 Update logo for documentation
  packages/docs/public/app-logo.png
Labels: ignore-for-release

#410 Uniform `<InputSelect>` style as other inputs
  packages/app-elements/src/ui/forms/InputSelect/styles.ts
  packages/app-elements/src/ui/internals/InputWrapper.tsx
Labels: bug

#405 Add `GTMProvider`
  packages/app-elements/package.json
  packages/app-elements/src/main.ts
  packages/app-elements/src/providers/GTMProvider.test.tsx
  packages/app-elements/src/providers/GTMProvider.tsx
  pnpm-lock.yaml
Labels: enhancement

#407 Add grid viewMode to `InputRadioGroup` + `HookedInputRadioGroup`
  packages/app-elements/src/main.ts
  packages/app-elements/src/styles/global.css
  packages/app-elements/src/ui/atoms/Card.tsx
  packages/app-elements/src/ui/forms/InputRadioGroup/HookedInputRadioGroup.tsx
  packages/app-elements/src/ui/forms/InputRadioGroup/InputRadioGroup.test.tsx
  packages/app-elements/src/ui/forms/InputRadioGroup/InputRadioGroup.tsx
  packages/app-elements/src/ui/forms/InputRadioGroup/index.tsx
  packages/docs/src/stories/forms/react-hook-form/HookedInputRadioGroup.stories.tsx
  packages/docs/src/stories/forms/ui/InputRadioGroup.stories.tsx
Labels: enhancement

#412 Update all dependencies to their latest version
  .npmrc
  package.json
  packages/app-elements/package.json
  packages/app-elements/src/helpers/resources.ts
  packages/app-elements/src/providers/TokenProvider/getInfoFromJwt.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
  packages/docs/package.json
  pnpm-lock.yaml
Labels: enhancement

#413 v1.5.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#414 Add missing `isLoading` prop to `InputRadioGroupProps`
  packages/app-elements/src/ui/forms/InputRadioGroup/InputRadioGroup.tsx
Labels: bug

#415 v1.5.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#418 Add `returns` in `ResourceOrderTimeline` component
  packages/app-elements/src/ui/resources/ResourceOrderTimeline.tsx
Labels: enhancement

#416 Add missing `feedback` to` HookedInputCheckbox`
  packages/app-elements/src/ui/forms/InputCheckbox/HookedInputCheckbox.tsx
Labels: bug

#420 Fix phrase in `Restocked on` badge of `ResourceLineItem` component
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
Labels: bug

#421 Add optional background color to Card and allow overflowing content
  packages/app-elements/src/ui/atoms/Alert.tsx
  packages/app-elements/src/ui/atoms/Card.test.tsx
  packages/app-elements/src/ui/atoms/Card.tsx
  packages/app-elements/src/ui/composite/CardDialog.tsx
  packages/app-elements/src/ui/composite/Timeline.tsx
  packages/app-elements/src/ui/forms/InputCheckboxGroup/InputCheckboxGroup.tsx
  packages/app-elements/src/ui/forms/InputRadioGroup/InputRadioGroup.tsx
  packages/app-elements/src/ui/forms/InputResourceGroup/FullList.tsx
  packages/app-elements/src/ui/forms/InputResourceGroup/InputResourceGroup.tsx
  packages/docs/src/stories/atoms/Card.stories.tsx
  packages/docs/src/stories/examples/FiltersCheckboxes.stories.tsx
Labels: breaking-change, enhancement

#417 Add parcel customs info
  packages/app-elements/src/ui/atoms/Hr.tsx
  packages/app-elements/src/ui/resources/ResourceShipmentParcels.mocks.tsx
  packages/app-elements/src/ui/resources/ResourceShipmentParcels.tsx
  packages/docs/src/stories/atoms/Hr.stories.tsx
  packages/docs/src/stories/resources/ResourceShipmentParcels.stories.tsx
Labels: enhancement

#422 v1.6.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#423 Add `stock_transfers` type in `ResourceListItem` component
  packages/app-elements/package.json
  packages/app-elements/src/dictionaries/returns.ts
  packages/app-elements/src/dictionaries/stockTransfers.ts
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/index.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/returns.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/stockTransfers.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/types.ts
  packages/app-elements/src/ui/resources/ResourceOrderSummary/AdjustTotalOverlay.tsx
  packages/docs/src/stories/resources/ResourceListItem.stories.tsx
  pnpm-lock.yaml
Labels: enhancement

#424 v1.6.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#403 `<InputCurrency>` can define which are the available `sign`s
  packages/app-elements/src/ui/forms/InputCurrency/InputCurrency.test.tsx
  packages/app-elements/src/ui/forms/InputCurrency/InputCurrency.tsx
  packages/app-elements/src/ui/forms/InputCurrency/utils.ts
  packages/app-elements/src/ui/resources/ResourceOrderSummary/AdjustTotalOverlay.tsx
  packages/docs/src/mocks/data/adjustments.js
  packages/docs/src/mocks/data/line_items.js
  packages/docs/src/stories/forms/ui/InputCurrency.stories.tsx
  packages/docs/src/stories/resources/ResourceOrderSummary.stories.tsx
Labels: enhancement

#427 Add RemoveButton component
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/atoms/RemoveButton.test.tsx
  packages/app-elements/src/ui/atoms/RemoveButton.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
  packages/app-elements/src/ui/resources/ResourceOrderSummary/DeleteCouponButton.tsx
  packages/docs/src/stories/atoms/RemoveButton.stories.tsx
Labels: enhancement

#429 Update SDK package to fix unwanted behaviors
  packages/app-elements/package.json
  packages/app-elements/src/ui/resources/ResourceOrderSummary/AdjustTotalOverlay.tsx
  pnpm-lock.yaml
Labels: bug

#430 v1.6.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#431 Add missing include in `ResourceOrderTimeline` to enable `returns` statuses
  packages/app-elements/src/ui/resources/ResourceOrderTimeline.tsx
Labels: bug

#432 v1.6.4
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#433 Use `return.stock_location` instead of `order.market`
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/returns.tsx
Labels: bug

#434 v1.6.5
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#436 Add `notes` field to ResourceAddress + new address preview layout
  packages/app-elements/src/main.ts
  packages/app-elements/src/styles/global.css
  packages/app-elements/src/ui/forms/InputTextArea/HookedInputTextArea.tsx
  packages/app-elements/src/ui/forms/InputTextArea/InputTextArea.test.tsx
  packages/app-elements/src/ui/forms/InputTextArea/InputTextArea.tsx
  packages/app-elements/src/ui/forms/InputTextArea/index.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.mocks.ts
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.test.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
  packages/docs/src/stories/forms/react-hook-form/HookedInputTextArea.stories.tsx
  packages/docs/src/stories/forms/ui/InputTextArea.stories.tsx
  packages/docs/src/stories/resources/ResourceAddress.stories.tsx
Labels: enhancement

#437 v1.6.6
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#439 Add missing `notes` field to address form schema
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
Labels: bug

#441 Add missing `useEffect` for `ResourceAddress` internal state
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
Labels: bug

#442 v1.7.1
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#444 Add GitHub and Google icons
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#445 Add `shipments` type to `ResourceLineItem` component
  packages/app-elements/src/dictionaries/shipments.ts
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/index.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/shipments.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/types.ts
  packages/docs/src/stories/resources/ResourceListItem.stories.tsx
Labels: enhancement

#446 Add optional `stock transfer` visualization in `ResourceLineItems` component
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/types.ts
  packages/docs/src/stories/resources/ResourceLineItems.stories.tsx
Labels: enhancement

#443 Replace `@ac-dev/countries-service` in ResourceAddress with static list of countries and states from cdn
  packages/app-elements/package.json
  packages/app-elements/src/mocks/data/countries.ts
  packages/app-elements/src/mocks/handlers.ts
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
  pnpm-lock.yaml
Labels: enhancement

#447 v1.7.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#450 Add `<OrganizationMenu>` component and icons
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
  packages/app-elements/src/ui/composite/OrganizationMenu.test.tsx
  packages/app-elements/src/ui/composite/OrganizationMenu.tsx
  packages/docs/src/stories/atoms/EmptyState.stories.tsx
  packages/docs/src/stories/composite/OrganizationMenu.stories.tsx
Labels: enhancement

#451 v1.8.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release
