Repository commercelayer/app-elements, pull requests merged in 2023-10, with the labels that each got.

#385 Remove image in readme
  packages/app-elements/README.md
Labels: ignore-for-release

#386 v1.0.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#387 Handle special case for `organization` resource on abilities page
  packages/docs/src/generate-abilities.mjs
Labels: documentation

#392 Allow to interact with inner checkbox in `InputCheckboxGroup`
  packages/app-elements/src/ui/forms/InputCheckboxGroup.test.tsx
  packages/app-elements/src/ui/forms/InputCheckboxGroup.tsx
Labels: bug

#391 Enforce `ResourceListItem` right column management
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/types.ts
Labels: bug

#393 Show `coupon_code` in the order summary and explode all applied promotions
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.test.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/AddCouponOverlay.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/AdjustTotalOverlay.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/DeleteCouponButton.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.test.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/index.ts
  packages/app-elements/src/ui/resources/ResourceOrderSummary/utils.tsx
  packages/docs/.storybook/main.ts
  packages/docs/.storybook/preview.tsx
  packages/docs/package.json
  packages/docs/src/mocks/data/orders.js
  packages/docs/src/stories/resources/ResourceLineItems.stories.tsx
  packages/docs/src/stories/resources/ResourceOrderSummary.stories.tsx
Labels: enhancement

#388 Allow `InputCheckboxGroup` to be used without a quantity
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/forms/InputCheckbox/InputCheckbox.tsx
  packages/app-elements/src/ui/forms/InputCheckboxGroup.tsx
  packages/app-elements/src/ui/forms/InputCheckboxGroup/HookedInputCheckboxGroup.tsx
  packages/app-elements/src/ui/forms/InputCheckboxGroup/InputCheckboxGroup.test.tsx
  packages/app-elements/src/ui/forms/InputCheckboxGroup/InputCheckboxGroup.tsx
  packages/app-elements/src/ui/forms/InputCheckboxGroup/InputCheckboxGroupItem.tsx
  packages/app-elements/src/ui/forms/InputCheckboxGroup/index.tsx
  packages/app-elements/src/ui/forms/InputCheckboxGroup/reducer.ts
  packages/app-elements/src/ui/forms/InputResourceGroup/Checkbox.tsx
  packages/app-elements/src/ui/forms/InputResourceGroup/FullList.tsx
  packages/app-elements/src/ui/forms/InputResourceGroup/InputResourceGroup.tsx
  packages/app-elements/src/ui/forms/InputResourceGroup/utils.ts
  packages/app-elements/src/ui/forms/InputSpinner/InputSpinner.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
  packages/docs/src/mocks/data/markets.js
  packages/docs/src/stories/forms/react-hook-form/HookedInputCheckboxGroup.stories.tsx
  packages/docs/src/stories/forms/ui/InputCheckboxGroup.stories.tsx
Labels: enhancement

#395 Show return `reason` in ResourceLineItem only if filled
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
Labels: bug

#394 Show all the adjustment line items + improve manual adjustment when oder editing
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts
  packages/app-elements/src/ui/resources/ResourceOrderSummary/AdjustTotalOverlay.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.test.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/utils.tsx
  packages/docs/.storybook/preview.tsx
  packages/docs/src/stories/resources/ResourceOrderSummary.mdx
  packages/docs/src/stories/resources/ResourceOrderSummary.stories.tsx
Labels: enhancement

#396 Fix hooks order in `ResourceTags` and remove unwanted props in `Tag` and `ListItem`
  packages/app-elements/src/ui/atoms/Tag.tsx
  packages/app-elements/src/ui/composite/ListItem.tsx
  packages/app-elements/src/ui/resources/ResourceTags.tsx
  packages/app-elements/src/utils/htmltags.test.ts
  packages/app-elements/src/utils/htmltags.ts
Labels: bug

#397 Add new `<Alert>` component
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/atoms/Alert.test.tsx
  packages/app-elements/src/ui/atoms/Alert.tsx
  packages/docs/src/stories/atoms/Alert.stories.tsx
Labels: enhancement

#398 Total amounts lower than 1 are now correctly rendered
  packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.test.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/utils.tsx
  packages/docs/src/stories/resources/ResourceOrderSummary.stories.tsx
Labels: bug

#399 Remove create/update/delete abilities for users with read-only permission on OrderSummary and OrderTimeline
  packages/app-elements/src/providers/TokenProvider/MockTokenProvider.tsx
  packages/app-elements/src/ui/composite/Timeline.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.test.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.tsx
  packages/app-elements/src/ui/resources/ResourceOrderTimeline.tsx
Labels: bug

#400 Handle more order statuses
  packages/app-elements/src/dictionaries/orders.ts
Labels: bug

#402 Handle error messages when adding a coupon in the order summary
  packages/app-elements/src/ui/internals/InputWrapper.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/AddCouponOverlay.tsx
  packages/docs/src/mocks/data/orders.js
Labels: bug

#404 Add `paddingSize` to the `<ListItem>` component
  packages/app-elements/src/ui/atoms/Alert.tsx
  packages/app-elements/src/ui/composite/ListItem.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
  packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/utils.tsx
  packages/docs/src/stories/resources/ResourceLineItems.stories.tsx
Labels: enhancement

#401 Handle missing order statuses
  packages/app-elements/src/dictionaries/orders.ts
Labels: bug

#408 v1.4.5
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release
