Repository commercelayer/app-elements, pull requests merged in 2023-12, with the labels that each got.

#452 Add `shipments` support to `ResourceTags` component
  packages/app-elements/src/ui/resources/ResourceTags.tsx
Labels: enhancement

#453 v1.8.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#455 Add `Pulse` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#454 Restrict `ResourceListItem` usage of `stock_transfers` to some defined statuses
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/shipments.tsx
Labels: bug

#456 v1.8.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#457 Rename `Icon` in `StatusIcon` and introduce new generic `Icon` component
  packages/app-elements/src/dictionaries/orders.ts
  packages/app-elements/src/dictionaries/returns.ts
  packages/app-elements/src/dictionaries/shipments.ts
  packages/app-elements/src/dictionaries/stockTransfers.ts
  packages/app-elements/src/dictionaries/types.ts
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/atoms/ButtonFilter.tsx
  packages/app-elements/src/ui/atoms/EmptyState.tsx
  packages/app-elements/src/ui/atoms/Icon/Icon.tsx
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
  packages/app-elements/src/ui/atoms/RadialProgress.tsx
  packages/app-elements/src/ui/atoms/SkeletonTemplate.test.tsx
  packages/app-elements/src/ui/atoms/SkeletonTemplate.tsx
  packages/app-elements/src/ui/atoms/StatusIcon.test.tsx
  packages/app-elements/src/ui/atoms/StatusIcon.tsx
  packages/app-elements/src/ui/atoms/Tag.tsx
  packages/app-elements/src/ui/composite/ListItem.tsx
  packages/app-elements/src/ui/composite/OrganizationMenu.tsx
  packages/app-elements/src/ui/composite/SearchBar.tsx
  packages/app-elements/src/ui/composite/Timeline.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/common.tsx
  packages/app-elements/src/ui/resources/ResourceShipmentParcels.tsx
  packages/docs/src/stories/atoms/Card.stories.tsx
  packages/docs/src/stories/atoms/SkeletonTemplate.stories.tsx
  packages/docs/src/stories/atoms/StatusIcon.stories.tsx
  packages/docs/src/stories/composite/CardDialog.stories.tsx
  packages/docs/src/stories/composite/ListItem.stories.tsx
  packages/docs/src/stories/examples/ListImports.stories.tsx
  packages/docs/src/stories/examples/ListResources.stories.tsx
  packages/docs/src/stories/examples/ListSkus.stories.tsx
  packages/docs/src/stories/examples/OrderHistory.stories.tsx
Labels: breaking-change, enhancement

#458 Add `icon` to `Badge` component
  packages/app-elements/src/ui/atoms/Badge/Badge.test.tsx
  packages/app-elements/src/ui/atoms/Badge/Badge.tsx
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
  packages/docs/src/stories/atoms/Badge.stories.tsx
Labels: enhancement

#459 v1.8.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#461 Set correct border radius in `OrganizationMenu`
  packages/app-elements/src/ui/composite/OrganizationMenu.tsx
Labels: bug

#460 Add new icons
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#462 Add header and icons in `Dropdown`
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
  packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
  packages/app-elements/src/ui/composite/Dropdown/DropdownDivider.tsx
  packages/app-elements/src/ui/composite/Dropdown/DropdownItem.tsx
  packages/app-elements/src/ui/composite/Dropdown/DropdownMenu.tsx
  packages/docs/src/stories/composite/Dropdown.stories.tsx
Labels: enhancement

#463 Add DropdownSearch component
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/composite/Dropdown/DropdownSearch.test.tsx
  packages/app-elements/src/ui/composite/Dropdown/DropdownSearch.tsx
  packages/app-elements/src/ui/composite/Dropdown/index.ts
  packages/docs/src/stories/composite/Dropdown.stories.tsx
Labels: enhancement

#464 Add Dropdown menu position
  packages/app-elements/src/ui/composite/Dropdown/Dropdown.test.tsx
  packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
  packages/app-elements/src/ui/composite/Dropdown/DropdownMenu.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/docs/src/stories/composite/Dropdown.stories.tsx
Labels: enhancement

#466 Add light background variant to `Overlay` component
  packages/app-elements/src/hooks/useOverlay.tsx
  packages/docs/src/stories/hooks/useOverlay.stories.tsx
Labels: enhancement

#465 Add new breakpoint for container
  packages/app-elements/tailwind.config.cjs
Labels: enhancement

#467 v1.9.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#470 Add `ScrollToTop` component and `PageLayout` behavior
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/atoms/ScrollToTop.tsx
  packages/app-elements/src/ui/composite/PageLayout.tsx
Labels: enhancement

#469 Add new icons
  packages/app-elements/src/ui/atoms/Icon/Icon.tsx
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#471 Replace `onGoBack` with `navigationButton` in PageHeading
  packages/app-elements/src/ui/atoms/PageHeading.test.tsx
  packages/app-elements/src/ui/atoms/PageHeading.tsx
  packages/app-elements/src/ui/composite/PageError.tsx
  packages/app-elements/src/ui/composite/PageLayout.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/AddCouponOverlay.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/AdjustTotalOverlay.tsx
  packages/app-elements/src/ui/resources/ResourceShipmentParcels.tsx
  packages/app-elements/src/ui/resources/ResourceTags.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FieldTimeRange.tsx
  packages/docs/src/stories/atoms/PageHeading.stories.tsx
  packages/docs/src/stories/composite/PageLayout.stories.tsx
  packages/docs/src/stories/examples/FiltersCheckboxes.stories.tsx
  packages/docs/src/stories/examples/ListImports.stories.tsx
  packages/docs/src/stories/examples/ListResources.stories.tsx
  packages/docs/src/stories/examples/ListSkus.stories.tsx
Labels: enhancement

#473 Update `InputReadonly` style
  packages/app-elements/src/ui/forms/InputReadonly.tsx
  packages/docs/src/stories/forms/ui/InputReadonly.stories.tsx
Labels: enhancement

#474 Add `alignItems` prop in `<Grid>` component
  packages/app-elements/src/ui/atoms/Grid.tsx
Labels: enhancement

#476 v1.9.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#478 Adjust grid alignment and responsiveness
  packages/app-elements/src/ui/atoms/Grid.tsx
  packages/docs/src/stories/atoms/Grid.stories.tsx
Labels: bug

#479 v1.9.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#480 Add `shipments.stock_transfers` support to `ResourceOrderTimeline`
  packages/app-elements/src/ui/resources/ResourceOrderTimeline.tsx
Labels: enhancement

#482 Hide `noOptionMessage` for `AsyncSelect` with empty search and empty `initialValues`
  packages/app-elements/src/ui/forms/InputSelect/AsyncComponent.tsx
Labels: enhancement

#483 v1.9.4
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#484 Add auto flow cols to grid component
  packages/app-elements/src/ui/atoms/Grid.tsx
Labels: enhancement

#485 v1.9.5
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#486 Add new icons
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#488 Add `unitsOfWeight` helper library
  packages/app-elements/src/helpers/unitsOfWeight.test.ts
  packages/app-elements/src/helpers/unitsOfWeight.ts
  packages/app-elements/src/main.ts
Labels: enhancement

#487 Allow `DropdownItem` to be used as anchor
  packages/app-elements/src/ui/composite/Dropdown/DropdownItem.test.tsx
  packages/app-elements/src/ui/composite/Dropdown/DropdownItem.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/docs/src/stories/composite/Dropdown.stories.tsx
Labels: enhancement

#489 v1.9.6
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release
