Repository commercelayer/app-elements, pull requests merged in 2024-06, with the labels that each got.

#666 Add optional footer in `InputSelect` menu
  packages/app-elements/src/ui/forms/InputSelect/HookedInputSelect.tsx
  packages/app-elements/src/ui/forms/InputSelect/InputSelect.tsx
  packages/app-elements/src/ui/forms/InputSelect/overrides.tsx
  packages/docs/src/stories/forms/react-hook-form/HookedInputSelect.stories.tsx
  packages/docs/src/stories/forms/ui/InputSelect.stories.tsx
Labels: enhancement

#667 Remove `defaultChecked` in `<HookedInputCheckbox>`
  packages/app-elements/src/ui/forms/InputCheckbox/HookedInputCheckbox.tsx
Labels: bug

#668 v2.0.4
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#669 Prevent content overlapping in `InputReadonly`
  packages/app-elements/src/ui/forms/InputReadonly.tsx
  packages/docs/src/stories/forms/ui/InputReadonly.stories.tsx
Labels: bug

#670 v2.0.5
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#671 Replace `getLastYearIsoRange` with `getLastYearIsoRange`
  packages/app-elements/src/helpers/date.test.ts
  packages/app-elements/src/helpers/date.ts
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.ts
  packages/docs/src/stories/utility/Date.stories.tsx
Labels: enhancement

#672 v2.0.6
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#673 Add quantity to line item options
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
Labels: enhancement

#674 v2.0.7
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#675 Expose `removeItem` method in ResourceList children prop
  packages/app-elements/src/ui/resources/ResourceList/ResourceList.tsx
Labels: enhancement

#676 Replace data-uri images in avatar presets with URLs from cdn.
  packages/app-elements/src/ui/atoms/Avatar.test.tsx
  packages/app-elements/src/ui/atoms/Avatar.tsx
  packages/app-elements/src/ui/atoms/Avatar.utils.ts
  packages/app-elements/src/ui/atoms/__snapshots__/Avatar.test.tsx.snap
Labels: enhancement

#677 v2.0.8
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#679 Show and edit `numbers` and `booleans` in `ResourceMetadata`
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
  packages/docs/src/mocks/data/customers.js
Labels: enhancement

#680 v2.0.9
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#681 Enforce support for `float` values in `ResourceMetadata`
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
  packages/docs/src/mocks/data/customers.js
Labels: bug

#682 v2.0.10
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release
