Repository commercelayer/app-elements, pull requests merged in 2024-11, with the labels that each got.

#822 Add arrowUp icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#824 Update `CodeEditor` test snapshot to include new resource
  packages/app-elements/src/ui/forms/CodeEditor/fetchCoreResourcesSuggestions.test.ts
Labels: ignore-for-release

#825 Update green color for text success
  packages/app-elements/src/ui/atoms/Text.test.tsx
  packages/app-elements/src/ui/atoms/Text.tsx
Labels: enhancement

#823 Add `info` prop in `DropdownItem`
  packages/app-elements/src/ui/composite/Dropdown/DropdownItem.tsx
  packages/app-elements/src/ui/composite/Dropdown/DropdownMenu.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/docs/src/stories/composite/Dropdown.stories.tsx
Labels: enhancement

#826 Dropdown when empty is no more visible
  packages/app-elements/src/ui/atoms/PageHeading/PageHeadingToolbar.test.tsx
  packages/app-elements/src/ui/atoms/PageHeading/PageHeadingToolbar.tsx
Labels: bug

#827 v3.1.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#828 Add new `key` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#829 v3.1.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#830 Add new `arrowsHorizontal` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#831 v3.1.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#834 Toolbar when navigationButton is not defined displays beside the title
  packages/app-elements/src/ui/atoms/PageHeading/PageHeading.test.tsx
  packages/app-elements/src/ui/atoms/PageHeading/PageHeading.tsx
  packages/app-elements/src/ui/composite/__snapshots__/PageLayout.test.tsx.snap
  packages/app-elements/src/ui/composite/__snapshots__/PageSkeleton.test.tsx.snap
  packages/docs/src/stories/atoms/PageHeading.stories.tsx
  packages/docs/src/stories/composite/PageLayout.stories.tsx
Labels: enhancement

#832 Set responsive paddings on `PageHeading`
  packages/app-elements/src/ui/atoms/PageHeading/PageHeading.test.tsx
  packages/app-elements/src/ui/atoms/PageHeading/PageHeading.tsx
  packages/app-elements/src/ui/composite/__snapshots__/PageLayout.test.tsx.snap
  packages/app-elements/src/ui/composite/__snapshots__/PageSkeleton.test.tsx.snap
Labels: enhancement

#836 Add new discord icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#837 v3.2.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#839 `HookedInput` with type number is a number and no more a string
  packages/app-elements/.eslintignore
  packages/app-elements/src/mocks/data/core_resources.ts
  packages/app-elements/src/mocks/handlers.ts
  packages/app-elements/src/ui/forms/CodeEditor/fetchCoreResourcesSuggestions.test.ts
  packages/app-elements/src/ui/forms/Input/HookedInput.tsx
Labels: bug

#838 Add storage methods in `TokenProvider`
  .github/workflows/pkg-pr-new.yaml
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  packages/app-elements/src/providers/createApp.tsx
Labels: enhancement

#841 Update dependencies
  package.json
  packages/app-elements/package.json
  packages/app-elements/src/helpers/resources.ts
  packages/app-elements/src/main.ts
  packages/app-elements/src/providers/CoreSdkProvider/useCoreApi.tsx
  packages/app-elements/src/providers/TokenProvider/MockTokenProvider.tsx
  packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetailsForm.tsx
  packages/docs/package.json
  packages/docs/src/components/CodeSample.tsx
  pnpm-lock.yaml
Labels: enhancement

#842 v3.3.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#843 Set fixed css filename in bundled output
  packages/app-elements/package.json
  packages/app-elements/tsconfig.json
  packages/app-elements/tsconfig.node.json
  packages/app-elements/vite.config.js
  pnpm-lock.yaml
Labels: bug

#844 v3.3.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#845 multi-async-select works well with `defaultValues`
  packages/app-elements/src/ui/forms/InputSelect/HookedInputSelect.tsx
  packages/docs/src/mocks/data/tags.js
  packages/docs/src/stories/forms/react-hook-form/HookedInputSelect.stories.tsx
Labels: bug

#798 Add `organization-config` schema to the CodeEditor component
  packages/app-elements/src/ui/forms/CodeEditor/CodeEditorComponent.tsx
  packages/docs/src/stories/forms/ui/CodeEditor.stories.tsx
Labels: enhancement
