Repository commercelayer/app-elements, pull requests merged in 2024-12, with the labels that each got.

#847 v3.5.0
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#850 Preserve `useResourceFilters` form state when opening date range overlay
  packages/app-elements/src/ui/resources/useResourceFilters/FieldTimeRange.tsx
Labels: bug

#851 Handle `formatDateRange` with timezone
  packages/app-elements/src/helpers/date.test.ts
  packages/app-elements/src/helpers/date.ts
Labels: bug

#852 Enforce Tooltip UI with max width
  packages/app-elements/src/ui/atoms/Tooltip.tsx
Labels: enhancement

#853 v3.5.1
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#854 Add `link` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#856 Replace cookie usage with session storage for app cross-linking
  packages/app-elements/src/helpers/useAppLinking.ts
Labels: enhancement

#858 v3.5.2
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#859 Add `arrowUDownLeft` and `sealPercent` icons
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#860 Remove `isValidGtmId` method from the `GTMProvider`
  packages/app-elements/src/providers/GTMProvider.test.tsx
  packages/app-elements/src/providers/GTMProvider.tsx
Labels: bug
