Repository commercelayer/app-elements, pull requests merged in 2024-04, with the labels that each got.

#598 `A` component can render as a button
  packages/app-elements/src/styles/vendor.css
  packages/app-elements/src/ui/atoms/A.test.tsx
  packages/app-elements/src/ui/atoms/A.tsx
  packages/app-elements/src/ui/atoms/Button.test.tsx
  packages/app-elements/src/ui/atoms/Button.tsx
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/app-elements/src/ui/internals/InteractiveElement.className.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
  packages/docs/src/stories/atoms/A.stories.tsx
  packages/docs/src/stories/atoms/Button.stories.tsx
  packages/docs/src/stories/composite/List.stories.tsx
Labels: enhancement

#599 Add resource filters adapter to transform SDK filter object to URL query string
  packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToUrlQuery.test.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToUrlQuery.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adapters.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adapters.types.ts
Labels: enhancement

#600 Remove `tag` prop from `ListItem` component
  packages/app-elements/src/ui/composite/CardDialog.tsx
  packages/app-elements/src/ui/composite/ListItem.test.tsx
  packages/app-elements/src/ui/composite/ListItem.tsx
  packages/app-elements/src/ui/forms/InputCheckboxGroup/InputCheckboxGroupItem.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/orders.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
  packages/docs/src/stories/atoms/Card.stories.tsx
  packages/docs/src/stories/atoms/SkeletonTemplate.stories.tsx
  packages/docs/src/stories/composite/CardDialog.stories.tsx
  packages/docs/src/stories/composite/ListDetails.stories.tsx
  packages/docs/src/stories/composite/ListDetailsItem.stories.tsx
  packages/docs/src/stories/composite/ListItem.stories.tsx
  packages/docs/src/stories/examples/ListImports.stories.tsx
  packages/docs/src/stories/examples/ListResources.stories.tsx
  packages/docs/src/stories/examples/ListSkus.stories.tsx
  packages/docs/src/stories/examples/OrderHistory.stories.tsx
  packages/docs/src/stories/forms/react-hook-form/HookedInputRadioGroup.stories.tsx
  packages/docs/src/stories/forms/react-hook-form/HookedInputSimpleSelect.stories.tsx
  packages/docs/src/stories/forms/react-hook-form/HookedInputSwitch.stories.tsx
  packages/docs/src/stories/forms/ui/InputCheckbox.stories.tsx
  packages/docs/src/stories/forms/ui/InputRadioGroup.stories.tsx
  packages/docs/src/stories/forms/ui/InputSimpleSelect.stories.tsx
  packages/docs/src/stories/forms/ui/InputSwitch.stories.tsx
  packages/docs/src/stories/resources/ResourceAddress.stories.tsx
  packages/docs/src/stories/resources/ResourceLineItems.stories.tsx
  packages/docs/src/stories/resources/ResourceList.stories.tsx
Labels: breaking-change, enhancement

#603 Enforce `button` behavior of `Card` component
  packages/app-elements/src/ui/atoms/Card.tsx
Labels: bug

#604 Enforce HTML `type` attribute of `ListItem` component
  packages/app-elements/src/ui/composite/ListItem.tsx
Labels: bug

#605 Set `white` background to focused `SearchBar`
  packages/app-elements/src/ui/composite/SearchBar.tsx
Labels: enhancement

#606 Add the style for the `a` element to the css
  packages/app-elements/src/styles/vendor.css
  packages/docs/src/stories/atoms/A.stories.tsx
Labels: enhancement

#607 Add the `boxed` variant to the `Table` component
  packages/app-elements/src/ui/atoms/Table/Table.test.tsx
  packages/app-elements/src/ui/atoms/Table/Table.tsx
  packages/app-elements/src/ui/atoms/Table/Th.tsx
  packages/docs/src/stories/atoms/Table.stories.tsx
Labels: enhancement

#608 Add `bg-white` to `Td` component
  packages/app-elements/src/ui/atoms/Table/Table.tsx
  packages/app-elements/src/ui/atoms/Table/Td.tsx
  packages/docs/.storybook/preview.tsx
  packages/docs/src/stories/atoms/Table.stories.tsx
Labels: bug

#612 Enhance visualization of return line items reason
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
Labels: enhancement

#611 Remove the `ButtonCard` component
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/atoms/ButtonCard.test.tsx
  packages/app-elements/src/ui/atoms/ButtonCard.tsx
  packages/docs/src/stories/atoms/ButtonCard.stories.tsx
Labels: breaking-change

#609 Enhance `ResourceMetadata` component
  packages/app-elements/src/hooks/useEditMetadataOverlay.tsx
  packages/app-elements/src/main.ts
  packages/app-elements/src/mocks/data/customers.ts
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/index.tsx
  packages/docs/src/mocks/data/customers.js
  packages/docs/src/mocks/handlers.js
  packages/docs/src/stories/resources/ResourceMetadata.stories.tsx
Labels: enhancement

#613 Use metrics API `carts` endpoint when fetching pending orders
  packages/app-elements/src/ui/resources/ResourceList/metricsApiClient.ts
Labels: bug

#614 v1.22.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#615 Enforce metadata show and fix updated payload
  packages/app-elements/src/hooks/useEditMetadataOverlay.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
Labels: ignore-for-release

#616 v1.22.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#617 Avoid duplicate keys when editing metadata
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/utils.test.ts
  packages/app-elements/src/ui/resources/ResourceMetadata/utils.ts
  packages/docs/src/mocks/data/customers.js
Labels: bug

#618 Update dependencies
  package.json
  packages/app-elements/package.json
  packages/app-elements/src/dictionaries/orders.ts
  packages/app-elements/src/helpers/resources.ts
  packages/docs/package.json
  pnpm-lock.yaml
Labels: enhancement

#619 v1.22.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#620 Make app (cross) linking work when in dashboard
  packages/app-elements/src/helpers/appsNavigation.test.ts
  packages/app-elements/src/helpers/appsNavigation.ts
Labels: enhancement

#621 v1.22.4
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#622 Add organization settings icons
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#624 Add Toolbar component
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/composite/Toolbar.test.tsx
  packages/app-elements/src/ui/composite/Toolbar.tsx
  packages/app-elements/src/ui/internals/InteractiveElement.className.ts
  packages/docs/src/stories/composite/Toolbar.stories.tsx
Labels: enhancement

#626 Add prop to `InputReadonly` to toggle hidden values
  packages/app-elements/src/styles/vendor.css
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
  packages/app-elements/src/ui/forms/InputReadonly.test.tsx
  packages/app-elements/src/ui/forms/InputReadonly.tsx
  packages/docs/src/stories/forms/ui/InputReadonly.stories.tsx
Labels: enhancement

#625 Add `wide` variant to `DropdownMenu`
  packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
  packages/app-elements/src/ui/composite/Dropdown/DropdownDivider.tsx
  packages/app-elements/src/ui/composite/Dropdown/DropdownMenu.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/docs/src/stories/composite/Dropdown.stories.tsx
Labels: enhancement

#629 Add `clockClockwise` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#631 Update workflow to latest versions
  .github/workflows/gh-pages.yaml
  .github/workflows/publish.yaml
  .github/workflows/test.yaml
  packages/docs/.storybook/main.ts
  packages/docs/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#633 Update action UI of `ResourceMetadata` component
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
Labels: enhancement

#634 v1.23.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#632 Update checkbox style
  packages/app-elements/src/ui/forms/InputCheckbox/InputCheckbox.tsx
  packages/app-elements/tailwind.config.cjs
Labels: enhancement

#635 Update section title color
  packages/app-elements/src/ui/atoms/Section.tsx
Labels: enhancement

#636 v1.23.3
  lerna.json
  package.json
  packages/app-elements/package.json
  packages/docs/package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#637 Add `useResourceAddressOverlay` hook and `ResourceAddressFormFields` component can be reused in other forms
  packages/app-elements/package.json
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.mocks.ts
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.test.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressFormFields.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/index.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/useResourceAddressOverlay.tsx
  packages/docs/package.json
  packages/docs/src/mocks/data/addresses.js
  packages/docs/src/mocks/handlers.js
  packages/docs/src/stories/resources/ResourceAddress.stories.tsx
  pnpm-lock.yaml
Labels: enhancement
