Repository commercelayer/app-elements, pull requests merged in 2024-08, with the labels that each got.

#695 Update badge colors for non-solid variant
  packages/app-elements/src/ui/atoms/Badge/Badge.tsx
  packages/app-elements/src/ui/atoms/Badge/badgeVariants.ts
  packages/app-elements/src/ui/atoms/PageHeading/PageHeading.test.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
Labels: enhancement

#694 Add `archive` and `shoppingBagOpen` icons
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#696 v2.2.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#697 Update style for badge solid variants
  packages/app-elements/src/ui/atoms/Badge/badgeVariants.ts
Labels: bug

#698 Add `arrowCircleUpRight` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#699 v2.2.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#700 Set toolbar icons weight to regular
  packages/app-elements/src/ui/composite/Toolbar.tsx
Labels: bug

#701 v2.2.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#702 Fix icon weights in toolbar
  packages/app-elements/src/ui/composite/Toolbar.tsx
Labels: bug

#703 v2.2.4
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#704 Show attachments with url in parcels
  packages/app-elements/src/ui/resources/ResourceShipmentParcels.mocks.tsx
  packages/app-elements/src/ui/resources/ResourceShipmentParcels.tsx
Labels: enhancement

#705 v2.2.5
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#708 v2.2.6
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#709 Add `shareFat` and `whatsappLogo` icons
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#710 v2.2.7
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#711 Refine UI of icon in `DropdownItem`
  packages/app-elements/src/ui/composite/Dropdown/DropdownItem.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Labels: enhancement

#707 TokenProvider: exposed parsed scopes found in access token
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/getInfoFromJwt.test.ts
  packages/app-elements/src/providers/TokenProvider/getInfoFromJwt.ts
  packages/app-elements/src/providers/TokenProvider/types.ts
  packages/app-elements/src/providers/TokenProvider/validateToken.ts
Labels: enhancement

#713 Manage word break in `InputReadonly`
  packages/app-elements/src/ui/forms/InputReadonly.tsx
Labels: bug

#714 v2.2.9
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#718 Add `flashlight` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#717 Adapt Metrics API orders in proper Core API order shape
  packages/app-elements/src/ui/resources/ResourceList/adaptMetricsOrderToCore.test.ts
  packages/app-elements/src/ui/resources/ResourceList/adaptMetricsOrderToCore.ts
  packages/app-elements/src/ui/resources/ResourceList/metricsApiClient.ts
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/orders.tsx
Labels: enhancement
