Repository commercelayer/app-elements, pull requests merged in 2024-03, with the labels that each got.

#577 Remove `filters` from the query prop (`FilteredList` component)
  packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
  packages/docs/src/stories/resources/useResourceFilters.stories.tsx
Labels: documentation

#578 Add new date helper `getLastYearIsoRange`
  packages/app-elements/src/helpers/date.test.ts
  packages/app-elements/src/helpers/date.ts
  packages/app-elements/src/main.ts
  packages/docs/src/components/CodeSample.tsx
  packages/docs/src/stories/utility/Date.stories.tsx
Labels: enhancement

#580 Input date time will never break into two lines
  packages/app-elements/src/ui/forms/InputDate/InputDateComponent.css
  packages/docs/src/stories/forms/ui/InputDate.stories.tsx
Labels: bug

#579 Enhance the `InputRadioGroup` component
  packages/app-elements/src/ui/forms/InputRadioGroup/HookedInputRadioGroup.tsx
  packages/app-elements/src/ui/forms/InputRadioGroup/InputRadioGroup.tsx
  packages/docs/src/stories/forms/react-hook-form/HookedInputRadioGroup.stories.tsx
  packages/docs/src/stories/forms/ui/InputRadioGroup.stories.tsx
Labels: enhancement

#582 Handle total usage for expiration
  packages/app-elements/src/dictionaries/promotions.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/promotions.tsx
Labels: bug

#583 Expose `debounceMs` prop to filters search bar
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersSearchBar.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
Labels: enhancement

#584 v1.17.2
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#585 Allow `ResourceList` to use Metrics API to fetch data.
  packages/app-elements/package.json
  packages/app-elements/src/ui/resources/ResourceList/ResourceList.tsx
  packages/app-elements/src/ui/resources/ResourceList/infiniteFetcher.ts
  packages/app-elements/src/ui/resources/ResourceList/metricsApiClient.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.test.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adapters.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adapters.types.ts
  packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
  pnpm-lock.yaml
Labels: enhancement

#588 v1.17.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#589 Add optional `flex` alignment to `Button` component
  packages/app-elements/src/ui/atoms/Button.test.tsx
  packages/app-elements/src/ui/atoms/Button.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
Labels: enhancement

#590 Replace variant `card` with `boxed` in `ListItem` component
  packages/app-elements/src/ui/composite/ListItem.tsx
  packages/docs/src/stories/atoms/SkeletonTemplate.stories.tsx
  packages/docs/src/stories/composite/ListDetails.stories.tsx
  packages/docs/src/stories/composite/ListItem.stories.tsx
Labels: breaking-change, enhancement

#591 v1.17.4
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#593 `hasCoupons` is now checking for the related promotion rule
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/promotions.tsx
Labels: bug

#592 InputReadonly to render multi line text content
  packages/app-elements/src/styles/vendor.css
  packages/app-elements/src/ui/atoms/CopyToClipboard.tsx
  packages/app-elements/src/ui/forms/InputReadonly.tsx
  packages/app-elements/tailwind.config.cjs
  packages/docs/.storybook/preview-head.html
  packages/docs/src/stories/forms/ui/InputReadonly.stories.tsx
Labels: enhancement

#594 Update `InputRadioGroup` ui
  packages/app-elements/src/ui/forms/InputRadioGroup/InputRadioGroup.tsx
Labels: enhancement

#596 `Card` can manage `href` and `onClick`
  packages/app-elements/src/ui/atoms/Card.tsx
  packages/app-elements/src/ui/atoms/StatusIcon.tsx
  packages/app-elements/tailwind.config.cjs
  packages/docs/src/stories/atoms/Card.stories.tsx
  packages/docs/src/stories/examples/Panel.stories.tsx
Labels: enhancement

#595 Handle amounts and currencies in sdk-to-metrics filters adapter
  packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.test.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adapters.ts
Labels: bug

#597 `Button` component is square when contains only one `Icon`
  packages/app-elements/src/ui/atoms/Button.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
  packages/docs/src/stories/atoms/Button.stories.tsx
Labels: enhancement
