Repository commercelayer/app-elements, pull requests merged in 2024-05, with the labels that each got.

#641 Refactor `PageSkeleton` with a single and generic layout
  packages/app-elements/src/main.ts
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  packages/app-elements/src/ui/atoms/PageHeading.tsx
  packages/app-elements/src/ui/composite/PageLayout.tsx
  packages/app-elements/src/ui/composite/PageSkeleton.test.tsx
  packages/app-elements/src/ui/composite/PageSkeleton.tsx
  packages/app-elements/src/ui/composite/SearchBar.tsx
  packages/app-elements/src/ui/composite/__snapshots__/PageSkeleton.test.tsx.snap
  packages/docs/src/stories/composite/PageSkeleton.stories.tsx
Labels: enhancement

#644 Set scrollToTop in `PageSkeleton`
  packages/app-elements/src/ui/composite/PageSkeleton.tsx
Labels: enhancement

#642 Enforce font sizes of `Button` component
  packages/app-elements/src/ui/composite/Dropdown/Dropdown.test.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/app-elements/src/ui/internals/InteractiveElement.className.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
Labels: enhancement

#646 Add `envelopeSimple` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#647 Add missing `Spacers` to validation api errors
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
Labels: bug

#643 Allow Dropdown to receive a plain jsx `<button>` tag as label
  packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
  packages/app-elements/src/utils/children.test.tsx
  packages/app-elements/src/utils/children.ts
  packages/docs/src/stories/composite/Dropdown.stories.tsx
Labels: bug

#648 v1.24.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#649 Avoid setting button font size with variant `link`
  packages/app-elements/src/ui/composite/Dropdown/Dropdown.test.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/app-elements/src/ui/internals/InteractiveElement.className.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
Labels: ignore-for-release

#650 v1.24.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#651 Remove `queryParam` in InputResourceGroup view all overlay
  packages/app-elements/src/ui/forms/InputResourceGroup/InputResourceGroup.tsx
Labels: bug

#652 Handle `ChunkLoadError` in `<ErrorBoundary>` component
  packages/app-elements/src/providers/ErrorBoundary.tsx
Labels: enhancement

#655 v1.24.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#656 Enhanced mobile behaviors of `PageHeading` title
  packages/app-elements/src/ui/atoms/PageHeading.tsx
  packages/app-elements/src/ui/composite/__snapshots__/PageLayout.test.tsx.snap
  packages/app-elements/src/ui/composite/__snapshots__/PageSkeleton.test.tsx.snap
  packages/docs/src/stories/composite/PageLayout.stories.tsx
Labels: enhancement

#657 Update `@commercelayer/sdk` to v6.x
  packages/app-elements/package.json
  packages/app-elements/src/helpers/resources.ts
  packages/app-elements/src/hooks/useEditMetadataOverlay.tsx
  packages/app-elements/src/providers/CoreSdkProvider/makeSdkClient.ts
  packages/app-elements/src/providers/CoreSdkProvider/useCoreApi.tsx
  packages/app-elements/src/providers/TokenProvider/MetaTags.tsx
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/makeSdkClient.ts
  packages/app-elements/src/providers/TokenProvider/types.ts
  packages/app-elements/src/providers/TokenProvider/validateToken.ts
  packages/app-elements/src/ui/forms/InputResourceGroup/FullList.tsx
  packages/app-elements/src/ui/forms/InputResourceGroup/InputResourceGroup.tsx
  packages/app-elements/src/ui/forms/InputResourceGroup/utils.ts
  packages/app-elements/src/ui/resources/ResourceList/ResourceList.tsx
  packages/app-elements/src/ui/resources/ResourceList/infiniteFetcher.ts
  packages/app-elements/src/ui/resources/ResourceList/metricsApiClient.ts
  packages/app-elements/src/ui/resources/ResourceList/reducer.ts
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
  packages/app-elements/src/ui/resources/ResourceTags.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FieldCurrencyRange.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/adaptFormValuesToSdk.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToUrlQuery.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToSdk.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adapters.types.ts
  packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
  pnpm-lock.yaml
Labels: enhancement

#659 Add currency options with top currencies for `InputSelect`
  packages/app-elements/src/helpers/currencies.test.ts
  packages/app-elements/src/helpers/currencies.ts
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/forms/InputSelect/InputSelect.tsx
  packages/app-elements/src/ui/forms/InputSelect/overrides.tsx
  packages/docs/src/stories/forms/ui/InputSelect.stories.tsx
Labels: enhancement

#660 Improve the `ResourceAddress` component
  packages/app-elements/src/ui/forms/ReactHookForm/HookedValidationApiError.tsx
  packages/app-elements/src/ui/forms/ReactHookForm/setApiFormErrors.ts
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.mocks.ts
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressFormFields.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/useResourceAddressOverlay.tsx
  packages/docs/src/mocks/data/addresses.js
  packages/docs/src/stories/resources/ResourceAddress.stories.tsx
Labels: enhancement

#661 Filter out placed orders when fetching carts with metrics-api
  packages/app-elements/src/ui/resources/ResourceList/metricsApiClient.ts
Labels: bug

#662 v2.0.1
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#663 Add new `delivered` status to shipments
  packages/app-elements/src/dictionaries/shipments.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
  packages/docs/src/stories/resources/ResourceListItem.stories.tsx
Labels: enhancement

#664 v2.0.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#665 Add new `usersThree` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement
