Repository commercelayer/app-elements, pull requests merged in 2024-09, with the labels that each got.

#720 Improve UX for the `AsyncCreatableSelect` component
  packages/app-elements/src/ui/forms/InputSelect/GenericAsyncComponent.tsx
Labels: enhancement

#719 Add new `calendarDots` and replace `flashLight` with `lightning`
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#721 Add props to control each single input in date range component
  packages/app-elements/src/ui/forms/InputDateRange/HookedInputDateRange.tsx
  packages/app-elements/src/ui/forms/InputDateRange/InputDateRange.tsx
  packages/docs/src/stories/forms/ui/InputDateRange.stories.tsx
Labels: enhancement

#723 Update all dependencies to the latest minor
  .ncurc.js
  package.json
  packages/app-elements/package.json
  packages/app-elements/src/helpers/resources.ts
  packages/app-elements/src/ui/atoms/Tabs.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToFormValues.ts
  packages/docs/package.json
  packages/docs/src/stories/atoms/CopyToClipboard.stories.tsx
  pnpm-lock.yaml
Labels: enhancement

#724 Refactor `InputReadonly` into `CodeBlock`
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/atoms/CodeBlock.test.tsx
  packages/app-elements/src/ui/atoms/CodeBlock.tsx
  packages/app-elements/src/ui/atoms/CopyToClipboard.tsx
  packages/app-elements/src/ui/composite/ListDetailsItem.tsx
  packages/app-elements/src/ui/forms/InputReadonly.test.tsx
  packages/app-elements/src/ui/forms/InputReadonly.tsx
  packages/app-elements/src/ui/internals/Overlay.tsx
  packages/docs/src/stories/atoms/CodeBlock.stories.tsx
  packages/docs/src/stories/forms/ui/InputReadonly.stories.tsx
Labels: breaking-change, enhancement

#726 Add support for `sku_list_items` in `ResourceListItem` component
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/index.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/skuListItem.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/types.ts
  packages/docs/src/stories/resources/ResourceListItem.stories.tsx
Labels: enhancement

#727 Add clickable related padding behavior to `ResourceListItem`
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
Labels: enhancement

#728 v2.3.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#729 Add swap item functionality to the `ResourceLineItems`
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.test.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
  packages/docs/src/stories/resources/ResourceLineItems.stories.tsx
Labels: enhancement

#731 Add overlay behavior to `ListItem` padding
  packages/app-elements/src/ui/composite/ListItem.tsx
Labels: enhancement

#733 Add `Copy` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#730 Allow to pass encoded `extras` to TokenProvider from URL query
  packages/app-elements/src/main.ts
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/extras.test.ts
  packages/app-elements/src/providers/TokenProvider/extras.ts
  packages/app-elements/src/providers/TokenProvider/getAccessTokenFromUrl.ts
  packages/app-elements/src/providers/TokenProvider/index.tsx
  packages/app-elements/src/providers/TokenProvider/storage.test.ts
  packages/app-elements/src/providers/TokenProvider/storage.ts
  packages/app-elements/src/providers/TokenProvider/types.ts
Labels: enhancement

#736 fix: add `Routes` related components to be shared across apps
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/composite/Routes/Routes.tsx
  packages/app-elements/src/ui/composite/Routes/index.tsx
  packages/app-elements/src/ui/composite/Routes/utils.test.ts
  packages/app-elements/src/ui/composite/Routes/utils.ts
  packages/docs/src/stories/utility/Route.data.tsx
Labels: enhancement

#737 Update primary color setup in TW config
  packages/app-elements/src/styles/vendor.css
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/app-elements/src/ui/internals/InteractiveElement.className.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
  packages/app-elements/tailwind.config.cjs
  packages/docs/src/stories/getting-started/001.welcome.mdx
Labels: enhancement

#739 Enforce `underline` behavior of links
  packages/app-elements/src/styles/vendor.css
  packages/app-elements/src/ui/composite/Dropdown/Dropdown.test.tsx
  packages/app-elements/src/ui/internals/InteractiveElement.className.ts
Labels: bug

#741 Replace old `focus` color with new `primary` color
  packages/app-elements/src/ui/forms/InputSelect/styles.ts
  packages/app-elements/src/ui/forms/InputSpinner/InputSpinner.tsx
  packages/app-elements/src/ui/internals/InputWrapper.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
  packages/app-elements/src/utils/text.test.ts
  packages/app-elements/tailwind.config.cjs
Labels: enhancement

#742 v2.3.8
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#743 Add violet palette to be used as dropdown item hover background
  packages/app-elements/src/ui/composite/Dropdown/DropdownItem.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/app-elements/tailwind.config.cjs
Labels: bug

#744 v2.3.9
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#745 Keep order number as string when converting from metrics order shape to core
  packages/app-elements/src/ui/resources/ResourceList/adaptMetricsOrderToCore.test.ts
  packages/app-elements/src/ui/resources/ResourceList/adaptMetricsOrderToCore.ts
Labels: bug

#746 v2.3.10
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#748 Allow custom alignments for Th component
  packages/app-elements/src/ui/atoms/Table/Th.tsx
  packages/docs/src/stories/atoms/Table.stories.tsx
Labels: bug

#749 Tune anchors style
  packages/app-elements/src/styles/vendor.css
  packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/app-elements/src/ui/internals/InteractiveElement.className.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
  packages/docs/src/stories/composite/Dropdown.stories.tsx
Labels: enhancement

#750 Add `QrCode` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#753 v2.3.12
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#752 Tweak `useResourceFilters` for metrics api
  packages/app-elements/src/ui/resources/ResourceList/ResourceList.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersSearchBar.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.test.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptSdkToMetrics.ts
  packages/app-elements/src/ui/resources/useResourceFilters/types.ts
Labels: enhancement

#754 v2.4.0
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#755 Prevent FiltersSearchBar useless rerendering
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.test.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersSearchBar.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
  packages/docs/src/stories/resources/useResourceFilters.stories.tsx
Labels: breaking-change, bug

#756 v2.5.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#757 restore `queryString` prop in FilterSearchBar
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.test.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersSearchBar.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
  packages/docs/src/stories/resources/useResourceFilters.stories.tsx
Labels: bug

#758 v2.5.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#759 Improve type of `query` prop of `ResourceList` component
  packages/app-elements/package.json
  packages/app-elements/src/ui/resources/ResourceList/ResourceList.tsx
  packages/app-elements/src/ui/resources/ResourceList/infiniteFetcher.ts
  pnpm-lock.yaml
Labels: enhancement

#761 Improve `Input` behaviors with `suffix` prop set
  packages/app-elements/src/ui/forms/Input/Input.tsx
Labels: bug

#763 Refactor `ResourceTags` component
  packages/app-elements/src/hooks/useEditTagsOverlay.tsx
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/atoms/Tag.tsx
  packages/app-elements/src/ui/resources/ResourceTags.tsx
Labels: enhancement
