Repository commercelayer/app-elements, pull requests merged in 2024-10, with the labels that each got.

#767 Improve `Resource`s components
  packages/app-elements/src/hooks/useEditMetadataOverlay.tsx
  packages/app-elements/src/hooks/useEditTagsOverlay.tsx
  packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetails.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
  packages/app-elements/src/ui/resources/ResourceTags.tsx
  packages/docs/src/stories/resources/ResourceMetadata.stories.tsx
  packages/docs/src/stories/resources/ResourceTags.stories.tsx
Labels: enhancement

#768 v2.7.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#769 Fix behavior of empty tags
  packages/app-elements/src/ui/resources/ResourceTags.tsx
Labels: bug

#770 v2.7.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#771 Show year in `ResourceDetails` component
  packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetails.tsx
Labels: enhancement

#772 v2.7.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#773 Fix `ResourceTags` edit ability check
  packages/app-elements/src/ui/resources/ResourceTags.tsx
Labels: bug

#774 v2.7.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#775 Refine `ResourceDetails` and `date` helper
  packages/app-elements/src/helpers/date.ts
  packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetails.tsx
Labels: bug

#776 v2.7.4
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#778 Enforce empty check of `ResourceDetails` components
  packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetails.tsx
Labels: bug

#779 v2.7.5
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#781 Add `arrowsDownUp` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#777 Add variant `table` in `ResourceList`
  packages/app-elements/src/ui/atoms/Table/Table.tsx
  packages/app-elements/src/ui/atoms/Table/Td.tsx
  packages/app-elements/src/ui/resources/ResourceList/ResourceList.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
  packages/docs/src/mocks/data/orders.js
  packages/docs/src/stories/resources/ResourceList.stories.tsx
Labels: enhancement

#782 Fix repaints of `ResourceMetadata` form
  packages/app-elements/src/hooks/useEditMetadataOverlay.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
Labels: enhancement

#784 Enhance `Section` component to support multiple actions via `actionButton` prop
  packages/app-elements/src/ui/atoms/Section.tsx
  packages/docs/src/stories/atoms/Section.stories.tsx
Labels: enhancement

#785 v2.8.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#787 Fix form payload of `ResourceMetadata` component
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
Labels: bug

#789 Enforce `ResourceMetadata` overlay
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
Labels: bug

#790 v2.8.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#792 Cleanup props of `ResourceMetadata` component
  packages/app-elements/src/hooks/useEditMetadataOverlay.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadataForm.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/index.tsx
  packages/docs/src/stories/resources/ResourceMetadata.stories.tsx
Labels: bug, enhancement

#793 v2.8.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#791 Update dependencies
  package.json
  packages/app-elements/package.json
  packages/app-elements/src/hooks/useDelayShow.test.tsx
  packages/app-elements/src/providers/TokenProvider/storage.test.ts
  packages/app-elements/src/ui/atoms/CodeBlock.test.tsx
  packages/docs/package.json
  pnpm-lock.yaml
Labels: enhancement

#783 Replace `ResourceList` with `useResourceList` hook
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/forms/InputResourceGroup/FullList.tsx
  packages/app-elements/src/ui/resources/ResourceList/ResourceList.test.tsx
  packages/app-elements/src/ui/resources/ResourceList/index.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
  packages/app-elements/src/ui/resources/useResourceList/VisibilityTrigger.test.tsx
  packages/app-elements/src/ui/resources/useResourceList/VisibilityTrigger.tsx
  packages/app-elements/src/ui/resources/useResourceList/adaptMetricsOrderToCore.test.ts
  packages/app-elements/src/ui/resources/useResourceList/adaptMetricsOrderToCore.ts
  packages/app-elements/src/ui/resources/useResourceList/index.tsx
  packages/app-elements/src/ui/resources/useResourceList/infiniteFetcher.ts
  packages/app-elements/src/ui/resources/useResourceList/metricsApiClient.ts
  packages/app-elements/src/ui/resources/useResourceList/reducer.ts
  packages/app-elements/src/ui/resources/useResourceList/useResourceList.test.tsx
  packages/app-elements/src/ui/resources/useResourceList/useResourceList.tsx
  packages/app-elements/src/ui/resources/useResourceList/utils.test.tsx
  packages/app-elements/src/ui/resources/useResourceList/utils.tsx
  packages/docs/src/stories/resources/ResourceList.stories.tsx
  packages/docs/src/stories/resources/useResourceFilters.stories.tsx
  packages/docs/src/stories/resources/useResourceList.stories.tsx
Labels: breaking-change, enhancement

#794 v2.9.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#796 Manage `refunded` return status
  packages/app-elements/src/dictionaries/returns.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
Labels: enhancement

#797 Adjust type for `emptyState` prop in `useResourceList` to accept any ReactNode
  packages/app-elements/src/ui/resources/useResourceList/useResourceList.tsx
Labels: bug

#795 Make `ResourceDetails` editable
  packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetails.tsx
  packages/app-elements/src/ui/resources/ResourceDetails/ResourceDetailsForm.tsx
  packages/app-elements/src/ui/resources/ResourceDetails/useEditDetailsOverlay.tsx
  packages/docs/src/stories/resources/ResourceDetails.stories.tsx
Labels: enhancement

#799 Restore original behavior of title size in resource list
  packages/app-elements/src/ui/resources/useResourceList/useResourceList.tsx
Labels: bug

#800 v2.10.1
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#801 Enhance `formatDate` time formatting
  packages/app-elements/src/helpers/date.test.ts
  packages/app-elements/src/helpers/date.ts
Labels: bug

#762 Add `CodeEditor` component
  .gitignore
  packages/app-elements/package.json
  packages/app-elements/src/main.ts
  packages/app-elements/src/mocks/setup.ts
  packages/app-elements/src/ui/forms/CodeEditor/CodeEditor.tsx
  packages/app-elements/src/ui/forms/CodeEditor/CodeEditorComponent.tsx
  packages/app-elements/src/ui/forms/CodeEditor/HookedCodeEditor.tsx
  packages/app-elements/src/ui/forms/CodeEditor/fetchCoreResourcesSuggestions.test.ts
  packages/app-elements/src/ui/forms/CodeEditor/fetchCoreResourcesSuggestions.ts
  packages/app-elements/src/ui/forms/CodeEditor/index.tsx
  packages/docs/src/stories/forms/react-hook-form/HookedCodeEditor.stories.tsx
  packages/docs/src/stories/forms/ui/CodeEditor.stories.tsx
  pnpm-lock.yaml
Labels: enhancement

#805 Clean up unwanted css class in InputWrapper
  packages/app-elements/src/ui/internals/InputWrapper.tsx
  packages/app-elements/src/ui/resources/ResourceLineItems/__snapshots__/ResourceLineItems.test.tsx.snap
Labels: bug

#807 v2.11.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#809 Add `ResourcePaymentMethod` component
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/resources/ResourcePaymentMethod.mocks.tsx
  packages/app-elements/src/ui/resources/ResourcePaymentMethod.test.tsx
  packages/app-elements/src/ui/resources/ResourcePaymentMethod.tsx
  packages/docs/src/stories/resources/ResourcePaymentMethod.stories.tsx
Labels: enhancement

#810 Allow to hide checkbox icon in desktop viewport
  packages/app-elements/src/ui/forms/InputCheckbox/InputCheckbox.tsx
  packages/app-elements/src/ui/forms/InputCheckboxGroup/InputCheckboxGroupItem.tsx
  packages/app-elements/src/ui/forms/InputResourceGroup/FullList.tsx
  packages/app-elements/src/ui/forms/InputResourceGroup/InputResourceGroup.tsx
  packages/docs/src/stories/examples/FiltersCheckboxes.stories.tsx
  packages/docs/src/stories/forms/ui/InputCheckbox.stories.tsx
Labels: enhancement

#811 Correct broken query in `MarketWithCurrencySelector`
  packages/app-elements/src/ui/forms/MarketWithCurrencySelector/HookedMarketWithCurrencySelector.tsx
Labels: bug

#812 v2.12.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#813 Add new props to better control UI in `ResourcePaymentMethod`
  packages/app-elements/src/ui/resources/ResourcePaymentMethod.test.tsx
  packages/app-elements/src/ui/resources/ResourcePaymentMethod.tsx
  packages/docs/src/stories/resources/ResourcePaymentMethod.stories.tsx
Labels: enhancement

#816 Manage FlexPromotions in the ResourceListItem component
  packages/app-elements/src/dictionaries/promotions.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/promotions.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/types.ts
  packages/docs/src/stories/resources/ResourceListItem.stories.tsx
Labels: enhancement

#814 v2.12.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#803 Remove `domain` prop in TokenProvider
  packages/app-elements/package.json
  packages/app-elements/src/providers/TokenProvider/TokenProvider.test.tsx
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/getOrganization.ts
  packages/app-elements/src/providers/TokenProvider/url.test.ts
  packages/app-elements/src/providers/TokenProvider/url.ts
  packages/app-elements/src/providers/TokenProvider/validateToken.test.ts
  packages/app-elements/src/providers/TokenProvider/validateToken.ts
  packages/app-elements/src/providers/createApp.tsx
  pnpm-lock.yaml
Labels: breaking-change, enhancement

#817 Update dependencies
  packages/app-elements/package.json
  packages/docs/package.json
  packages/docs/src/generate-abilities.mjs
  pnpm-lock.yaml
Labels: enhancement

#818 v3.0.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#819 CodeEditor better manages onChange event
  packages/app-elements/src/ui/forms/CodeEditor/CodeEditorComponent.tsx
  packages/app-elements/src/ui/forms/CodeEditor/HookedCodeEditor.tsx
Labels: bug

#821 v3.0.2
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release
