Repository commercelayer/app-elements, pull requests merged in 2024-02, with the labels that each got.

#535 `InputCheckbox` can accepts ReactNode as children
  packages/app-elements/src/ui/forms/InputCheckbox/InputCheckbox.tsx
  packages/docs/src/stories/forms/ui/InputCheckbox.stories.tsx
Labels: enhancement

#536 Add `className` to InputRadioGroup > OptionItem
  packages/app-elements/src/ui/forms/InputRadioGroup/InputRadioGroup.tsx
  packages/docs/src/stories/forms/ui/InputRadioGroup.stories.tsx
Labels: enhancement

#537 Aallow TokenProvider to persist token using custom `organizationSlug`
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/storage.test.ts
  packages/app-elements/src/providers/TokenProvider/storage.ts
Labels: enhancement

#538 Fix type of `app` props in `appsNavigation` helper
  packages/app-elements/src/helpers/appsNavigation.ts
Labels: bug

#539 v1.13.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#542 v1.13.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#543 Update all dependencies to the latest
  .github/workflows/gh-pages.yaml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  package.json
  packages/app-elements/package.json
  packages/app-elements/src/helpers/appsNavigation.test.ts
  packages/app-elements/src/helpers/attachments.ts
  packages/app-elements/src/helpers/route.ts
  packages/app-elements/src/hooks/useOverlay.test.tsx
  packages/app-elements/src/hooks/useOverlay.tsx
  packages/app-elements/src/main.test.ts
  packages/app-elements/src/mocks/data/countries.ts
  packages/app-elements/src/mocks/data/customers.ts
  packages/app-elements/src/mocks/handlers.ts
  packages/app-elements/src/ui/atoms/CopyToClipboard.test.tsx
  packages/app-elements/src/ui/atoms/Hr.test.tsx
  packages/app-elements/src/ui/atoms/RadialProgress.tsx
  packages/app-elements/src/ui/atoms/SkeletonTemplate.tsx
  packages/app-elements/src/ui/forms/InputCurrencyRange.tsx
  packages/app-elements/src/ui/forms/InputSelect/utils.ts
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddressForm.tsx
  packages/app-elements/src/ui/resources/ResourceList/reducer.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
  packages/app-elements/src/ui/resources/ResourceOrderSummary/AddCouponOverlay.tsx
  packages/app-elements/src/utils/children.ts
  packages/docs/.storybook/preview.tsx
  packages/docs/package.json
  packages/docs/public/mockServiceWorker.js
  packages/docs/src/mocks/browser.js
  packages/docs/src/mocks/data/adjustments.js
  packages/docs/src/mocks/data/bundles.js
  packages/docs/src/mocks/data/customers.js
  packages/docs/src/mocks/data/line_items.js
  packages/docs/src/mocks/data/markets.js
  packages/docs/src/mocks/data/orders.js
  packages/docs/src/mocks/data/tags.js
  packages/docs/src/stories/getting-started/004.CoreSdkProvider.stories.tsx
  packages/docs/src/stories/resources/ResourceOrderSummary.stories.tsx
  pnpm-lock.yaml
Labels: enhancement

#545 v1.14.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#546 Prevent children of ListDetailsItem to break its layout
  packages/app-elements/src/ui/atoms/CopyToClipboard.tsx
  packages/app-elements/src/ui/composite/ListDetailsItem.tsx
  packages/docs/src/stories/atoms/CopyToClipboard.stories.tsx
  packages/docs/src/stories/composite/ListDetailsItem.stories.tsx
Labels: enhancement

#547 v1.14.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#548 Grouped button filter is now correctly rendered when multiple relationship-resources are selected as filter value
  packages/app-elements/src/mocks/handlers.ts
  packages/app-elements/src/ui/resources/useResourceFilters/FilterNav.test.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.tsx
Labels: bug

#549 Tune breakpoints and container size
  packages/app-elements/src/ui/atoms/Container.tsx
  packages/app-elements/src/ui/atoms/Grid.tsx
  packages/app-elements/src/ui/composite/Dropdown/DropdownMenu.tsx
  packages/app-elements/src/ui/composite/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/app-elements/src/ui/composite/__snapshots__/PageLayout.test.tsx.snap
  packages/app-elements/tailwind.config.cjs
Labels: enhancement

#550 v1.14.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#435 Remove ResourceOrderSummary component and all order trigger attributes
  packages/app-elements/src/dictionaries/orders.ts
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts
  packages/app-elements/src/ui/resources/ResourceOrderSummary/AddCouponOverlay.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/AdjustTotalOverlay.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/DeleteCouponButton.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.test.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/ResourceOrderSummary.tsx
  packages/app-elements/src/ui/resources/ResourceOrderSummary/index.ts
  packages/app-elements/src/ui/resources/ResourceOrderSummary/utils.tsx
  packages/docs/src/stories/getting-started/001.welcome.mdx
  packages/docs/src/stories/resources/ResourceOrderSummary.mdx
  packages/docs/src/stories/resources/ResourceOrderSummary.stories.tsx
Labels: breaking-change

#553 Add `Tooltip` component
  packages/app-elements/package.json
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/atoms/Tooltip.test.tsx
  packages/app-elements/src/ui/atoms/Tooltip.tsx
  packages/docs/src/stories/atoms/Tooltip.stories.tsx
  pnpm-lock.yaml
Labels: enhancement

#554 v1.14.5
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#555 `id` is now optional for the `Tooltip` component
  packages/app-elements/src/ui/atoms/Tooltip.test.tsx
  packages/app-elements/src/ui/atoms/Tooltip.tsx
  packages/docs/src/stories/atoms/Tooltip.stories.tsx
Labels: enhancement

#552 Solve `CVE-2023-42282` vulnerability
  package.json
  packages/app-elements/package.json
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
  packages/docs/package.json
  pnpm-lock.yaml
Labels: ignore-for-release, security, p1

#558 v1.14.6
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#559 Hide `Dropdown` if no items are set
  packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
Labels: bug

#560 Improve `Stack` spacings and add `mobile` vertical behavior
  packages/app-elements/src/ui/atoms/Stack.tsx
Labels: enhancement

#561 `GetParams` type better works with `createTypedRoute`
  packages/app-elements/src/helpers/route.ts
Labels: enhancement

#562 Improve integration between Dashboard and Apps
  packages/app-elements/src/main.ts
  packages/app-elements/src/providers/CoreSdkProvider/useCoreApi.tsx
  packages/app-elements/src/providers/TokenProvider/MockTokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/reducer.ts
  packages/app-elements/src/providers/TokenProvider/types.ts
  packages/app-elements/src/providers/createApp.tsx
  packages/app-elements/src/ui/atoms/PageHeading.test.tsx
  packages/app-elements/src/ui/atoms/PageHeading.tsx
  packages/app-elements/src/ui/composite/HomePageLayout.test.tsx
  packages/app-elements/src/ui/composite/HomePageLayout.tsx
  packages/app-elements/src/ui/composite/PageLayout.tsx
  packages/docs/src/stories/atoms/PageHeading.stories.tsx
Labels: enhancement

#565 Add `trash` icon support
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#564 Add `defaultTab` to `Tabs` component
  packages/app-elements/src/ui/atoms/Tabs.tsx
Labels: enhancement

#567 v1.15.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#568 Update createApp to include appSlug parameter
  packages/app-elements/src/main.ts
  packages/app-elements/src/providers/createApp.tsx
Labels: enhancement

#569 v1.15.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#570 Show the option label when selected value is a string
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.test.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/adaptFormValuesToSdk.test.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToFormValues.test.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToSdk.test.ts
  packages/app-elements/src/ui/resources/useResourceFilters/mockedInstructions.ts
  packages/docs/src/stories/resources/useResourceFilters.stories.tsx
Labels: bug

#571 Enhance the `useResourceFilters` hook
  packages/app-elements/src/ui/resources/useResourceFilters/FieldOptions.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FieldTextSearch.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersForm.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.test.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersSearchBar.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/adaptFormValuesToSdk.test.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptFormValuesToSdk.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptFormValuesToUrlQuery.test.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToFormValues.test.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToFormValues.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToSdk.test.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToSdk.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToUrlQuery.test.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adaptUrlQueryToUrlQuery.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adapters.ts
  packages/app-elements/src/ui/resources/useResourceFilters/adapters.types.ts
  packages/app-elements/src/ui/resources/useResourceFilters/mockedInstructions.ts
  packages/app-elements/src/ui/resources/useResourceFilters/types.ts
  packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
  packages/docs/src/stories/resources/useResourceFilters.stories.tsx
Labels: enhancement

#573 Add `resources` to `TokenProviderAllowedApp`
  packages/app-elements/src/providers/TokenProvider/types.ts
Labels: enhancement

#575 Add `SkeletonTemplate` support for `CopyToClipboard`
  packages/app-elements/src/ui/atoms/CopyToClipboard.tsx
  packages/app-elements/src/ui/atoms/SkeletonTemplate.tsx
  packages/docs/src/stories/atoms/SkeletonTemplate.stories.tsx
Labels: bug

#576 v1.15.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release
