Repository commercelayer/app-elements, pull requests merged in 2024-01, with the labels that each got.

#491 Add new icons
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#490 Add border variants to Alert
  packages/app-elements/src/ui/atoms/Alert.tsx
Labels: enhancement

#492 v1.9.7
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#493 Rename icons
  .vscode/settings.json
  packages/app-elements/src/ui/atoms/ButtonFilter.test.tsx
  packages/app-elements/src/ui/atoms/Hint.test.tsx
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
  packages/app-elements/src/ui/atoms/RadialProgress.test.tsx
  packages/app-elements/src/ui/composite/OrganizationMenu.tsx
  packages/app-elements/src/ui/resources/useResourceFilters/FiltersNav.tsx
  packages/docs/src/stories/atoms/ButtonFilter.stories.tsx
  packages/docs/src/stories/atoms/Card.stories.tsx
  packages/docs/src/stories/atoms/EmptyState.stories.tsx
  packages/docs/src/stories/atoms/Hint.stories.tsx
  packages/docs/src/stories/atoms/Icon.stories.tsx
  packages/docs/src/stories/composite/CardDialog.stories.tsx
  packages/docs/src/stories/composite/ListItem.stories.tsx
  packages/docs/src/stories/forms/ui/InputSelect.stories.tsx
Labels: enhancement

#494 Allow to use multiple Stack
  packages/app-elements/src/ui/atoms/Stack.tsx
  packages/docs/src/stories/atoms/Stack.stories.tsx
Labels: enhancement

#495 Add gap `none` to Card
  packages/app-elements/src/ui/atoms/Card.tsx
  packages/docs/src/stories/atoms/Card.stories.tsx
Labels: enhancement

#498 Promotion is disabled when `disable_at` is set
  packages/app-elements/src/dictionaries/promotions.ts
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
Labels: bug

#501 `distanceToNow` option on `formatDate` now consider also future dates
  packages/app-elements/src/helpers/date.test.ts
  packages/app-elements/src/helpers/date.ts
  packages/docs/src/stories/utility/Date.stories.tsx
Labels: bug

#499 Add new icons
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#500 Enforce `domain` when production URL is matched
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/url.test.ts
  packages/app-elements/src/providers/TokenProvider/url.ts
Labels: enhancement

#503 Add `large` size to `Avatar` component
  packages/app-elements/src/ui/atoms/Avatar.tsx
Labels: enhancement

#502 Add `ButtonCard` component
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/atoms/ButtonCard.test.tsx
  packages/app-elements/src/ui/atoms/ButtonCard.tsx
  packages/docs/src/stories/atoms/ButtonCard.stories.tsx
Labels: enhancement

#506 v1.11.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#507 Fix typings of `ButtonImageSelect` component
  packages/app-elements/src/ui/atoms/ButtonImageSelect.tsx
Labels: bug

#508 v1.11.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#510 v1.11.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#511 Remove not used `SwitchMode` component
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/composite/SwitchMode.test.tsx
  packages/app-elements/src/ui/composite/SwitchMode.tsx
  packages/docs/src/stories/composite/SwitchMode.stories.tsx
Labels: enhancement

#513 Enforce `TokenProvider` allowed apps
  packages/app-elements/src/providers/TokenProvider/types.ts
Labels: enhancement

#505 Allow to use library with custom Tailwind CSS setup (from consumer app)
  packages/app-elements/package.json
  packages/app-elements/src/styles/global.css
  packages/app-elements/src/styles/vendor.css
  packages/app-elements/src/ui/forms/InputDate/InputDateComponent.tsx
  packages/app-elements/tailwind.config.cjs
  packages/docs/src/stories/getting-started/001.welcome.mdx
  pnpm-lock.yaml
Labels: enhancement

#515 Add `createRoute` and `createTypedRoute` helpers
  packages/app-elements/src/helpers/route.test.ts
  packages/app-elements/src/helpers/route.ts
  packages/app-elements/src/main.ts
  packages/docs/src/components/CodeSample.tsx
  packages/docs/src/stories/utility/Route.stories.tsx
Labels: enhancement

#516 v1.12.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#517 Add dashboard allowed app in token provider
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/types.ts
Labels: enhancement

#518 Prevent failed transaction to be displayed as a success message
  packages/app-elements/src/dictionaries/orders.ts
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/resources/ResourceOrderTimeline.tsx
Labels: bug

#520 v1.12.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#521 Make `useOverlay` reactive on `queryParam` changes
  packages/app-elements/src/hooks/useOverlay.tsx
Labels: bug

#523 Add `LockSimple` Phosphor icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#524 Add value `1` to `Spacer` component
  packages/app-elements/src/ui/atoms/Spacer.tsx
Labels: enhancement

#525 v1.12.2
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#526 Fix `lockSimple` icon key name
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: bug

#522 Few improvements for the `InputSelect` component
  packages/app-elements/src/ui/forms/InputSelect/AsyncComponent.tsx
  packages/app-elements/src/ui/forms/InputSelect/HookedInputSelect.tsx
  packages/app-elements/src/ui/forms/InputSelect/InputSelect.test.tsx
  packages/app-elements/src/ui/forms/InputSelect/InputSelect.tsx
  packages/app-elements/src/ui/forms/InputSelect/SelectComponent.tsx
  packages/app-elements/src/ui/forms/InputSelect/styles.ts
  packages/docs/src/stories/forms/react-hook-form/HookedInputSelect.stories.tsx
  packages/docs/src/stories/forms/ui/InputSelect.stories.tsx
Labels: enhancement

#527 `app-elements` can run on Next.js
  packages/app-elements/src/providers/TokenProvider/getAccessTokenFromUrl.ts
  packages/app-elements/src/providers/TokenProvider/storage.ts
  packages/app-elements/src/providers/TokenProvider/url.ts
  packages/app-elements/vite.config.ts
Labels: enhancement

#528 Remove overflow hidden from `ListDetailsItem`
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
  packages/app-elements/src/ui/composite/ListDetailsItem.tsx
  packages/docs/src/stories/composite/ListDetailsItem.stories.tsx
Labels: enhancement

#529 Add documentation for currency helpers
  packages/docs/src/stories/utility/Currency.stories.tsx
Labels: documentation

#530 Add some new icons
  packages/app-elements/src/ui/atoms/Icon/Icon.tsx
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#531 Add an `API` badge when promotion is created from outside the app
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/promotions.tsx
Labels: enhancement

#533 Add ability to show additional Elements when checkbox is checked
  packages/app-elements/src/ui/atoms/SkeletonTemplate.tsx
  packages/app-elements/src/ui/composite/ListDetailsItem.tsx
  packages/app-elements/src/ui/forms/InputCheckbox/HookedInputCheckbox.tsx
  packages/app-elements/src/ui/forms/InputCheckbox/InputCheckbox.tsx
  packages/app-elements/src/utils/array.ts
  packages/app-elements/src/utils/children.test.tsx
  packages/app-elements/src/utils/children.ts
  packages/docs/src/stories/forms/react-hook-form/HookedInputCheckbox.stories.tsx
  packages/docs/src/stories/forms/ui/InputCheckbox.stories.tsx
Labels: enhancement

#534 The `HookedInputCheckbox` component will set all Hooked children to undefined when unchecked
  packages/app-elements/src/ui/forms/InputCheckbox/HookedInputCheckbox.tsx
  packages/docs/src/stories/forms/react-hook-form/HookedInputCheckbox.stories.tsx
Labels: bug
