Repository commercelayer/app-elements, pull requests merged in 2025-03, with the labels that each got.

#904 Increase pageSize of resource tags list
  packages/app-elements/src/ui/resources/ResourceTags.tsx
Labels: enhancement

#905 v5.1.0
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#906 Add `type="hidden"` to the Input and HookedInput components
  packages/app-elements/src/ui/forms/Input/Input.tsx
Labels: enhancement

#908 v5.1.1
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#909 Refine ui of `InputSwitch` component
  packages/app-elements/src/ui/forms/InputSwitch/InputSwitch.tsx
Labels: enhancement

#910 Add `gear` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#911 v5.1.2
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#912 Increase top margin of SearchBar
  packages/app-elements/src/ui/resources/useResourceFilters/useResourceFilters.tsx
Labels: enhancement

#913 v5.1.3
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#914 Enforce types of `SkeletonTemplate`
  packages/app-elements/src/ui/atoms/SkeletonTemplate.tsx
Labels: enhancement

#915 Fix updated tags mutation
  packages/app-elements/src/hooks/useEditTagsOverlay.tsx
Labels: bug

#916 v5.1.4
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#917 Handle order with status `approved:free:in_progress`
  packages/app-elements/src/dictionaries/orders.ts
Labels: bug

#918 Prevent date picker to be hidden by other elements
  packages/app-elements/src/ui/forms/InputDate/InputDateComponent.css
Labels: bug

#920 Add translation for coupon code min length
  packages/app-elements/src/locales/en.ts
  packages/app-elements/src/locales/it.ts
Labels: enhancement

#921 v5.1.5
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release
