Repository commercelayer/app-elements, pull requests merged in 2025-01, with the labels that each got.

#861 Fix long text visualization in `ResourceMetadata` component
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
  packages/docs/src/mocks/data/customers.js
Labels: bug

#862 Relax shipping rates schema
  packages/app-elements/src/helpers/tracking.ts
  packages/app-elements/src/ui/resources/ResourceShipmentParcels.tsx
Labels: bug

#863 v3.5.5
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#865 Enhance `ResourceAddress` visualization
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.mocks.ts
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.test.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
Labels: enhancement

#866 v4.0.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#867 Read tags limit from feature flag
  packages/app-elements/src/hooks/useEditTagsOverlay.tsx
Labels: enhancement

#869 Enhance shipment list item
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.mocks.ts
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/shipments.tsx
Labels: enhancement

#870 v4.1.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#871 Avoid empty `payment_response` visualization
  packages/app-elements/package.json
  packages/app-elements/src/ui/resources/ResourcePaymentMethod.tsx
Labels: bug

#873 Add `diamonds-four` and `trend-up` icons
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement

#872 Add an 'input' variant to the Button component
  packages/app-elements/src/styles/vendor.css
  packages/app-elements/src/ui/internals/InteractiveElement.className.ts
  packages/docs/src/stories/atoms/Button.stories.tsx
Labels: enhancement

#874 Increase height when button uses the input variant
  packages/app-elements/src/ui/internals/InteractiveElement.className.ts
Labels: bug

#875 Extract the `Address` component from the `ResourceAddress` component
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/composite/Address.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.test.tsx
  packages/app-elements/src/ui/resources/ResourceAddress/ResourceAddress.tsx
  packages/docs/src/stories/composite/Address.stories.tsx
Labels: enhancement

#876 Add `wrench` icon
  packages/app-elements/src/ui/atoms/Icon/icons.tsx
Labels: enhancement
