Repository commercelayer/app-elements, pull requests merged in 2025-08, with the labels that each got.

#982 Rule engine for price rules
  packages/app-elements/src/mocks/setup.ts
  packages/app-elements/src/styles/global.css
  packages/app-elements/src/ui/forms/CodeEditor/CodeEditorComponent.tsx
  packages/app-elements/src/ui/forms/RuleEngine/Action/ActionListItem.tsx
  packages/app-elements/src/ui/forms/RuleEngine/RuleEngineComponent.tsx
  packages/app-elements/src/ui/forms/RuleEngine/RuleEngineContext.tsx
  packages/app-elements/src/ui/forms/RuleEngine/index.test.tsx
  packages/app-elements/src/ui/forms/RuleEngine/utils.ts
  packages/docs/src/stories/forms/react-hook-form/HookedCodeEditor.stories.tsx
  packages/docs/src/stories/forms/ui/CodeEditor.stories.tsx
  packages/docs/src/stories/forms/ui/RuleEngine.stories.tsx
Labels: enhancement

#983 Tune overlay drawer css
  packages/app-elements/src/ui/internals/Overlay.tsx
Labels: bug

#984 v6.0.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#987 Autocomplete resource path on the `RuleEngine` component
  packages/app-elements/src/locales/en.ts
  packages/app-elements/src/locales/it.ts
  packages/app-elements/src/ui/forms/CodeEditor/fetchCoreResourcesSuggestions.test.ts
  packages/app-elements/src/ui/forms/InputSelect/GenericAsyncComponent.tsx
  packages/app-elements/src/ui/forms/InputSelect/InputSelect.tsx
  packages/app-elements/src/ui/forms/RuleEngine/Action/ActionListItem.tsx
  packages/app-elements/src/ui/forms/RuleEngine/Condition/ConditionListItem.tsx
  packages/app-elements/src/ui/forms/RuleEngine/InputResourcePath.tsx
  packages/app-elements/src/ui/forms/RuleEngine/RuleEngineComponent.tsx
  packages/app-elements/src/ui/forms/RuleEngine/RuleEngineContext.tsx
  packages/app-elements/src/ui/forms/RuleEngine/__snapshots__/index.test.tsx.snap
  packages/app-elements/src/ui/internals/InteractiveElement.className.ts
  packages/docs/src/stories/forms/ui/InputSelect.stories.tsx
Labels: enhancement

#988 Use deep clone when setting a path
  packages/app-elements/src/ui/forms/RuleEngine/RuleEngineContext.tsx
  packages/docs/src/stories/forms/ui/RuleEngine.stories.tsx
Labels: bug
