Repository commercelayer/app-elements, pull requests merged in 2025-02, with the labels that each got.

#877 Add `shouldRender` method in `<TokenProvider>`
  packages/app-elements/package.json
  packages/app-elements/src/providers/TokenProvider/MockTokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/ResourceListItem.tsx
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/orders.tsx
  pnpm-lock.yaml
Labels: enhancement

#878 v4.4.0
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#879 Avoid wrong timezone conversions in `formatDateRange` helper
  packages/app-elements/src/helpers/date.test.ts
  packages/app-elements/src/helpers/date.ts
  packages/app-elements/src/ui/forms/InputDateRange/InputDateRange.tsx
Labels: bug

#880 Removed unused shouldRender method
  packages/app-elements/package.json
  packages/app-elements/src/providers/TokenProvider/MockTokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  pnpm-lock.yaml
Labels: enhancement

#881 Remove `organization` from the TokenProvider
  packages/app-elements/src/hooks/useEditTagsOverlay.tsx
  packages/app-elements/src/providers/TokenProvider/MetaTags.tsx
  packages/app-elements/src/providers/TokenProvider/MockTokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/TokenProvider.test.tsx
  packages/app-elements/src/providers/TokenProvider/TokenProvider.tsx
  packages/app-elements/src/providers/TokenProvider/getOrganization.ts
  packages/app-elements/src/providers/TokenProvider/reducer.ts
  packages/app-elements/src/providers/TokenProvider/types.ts
  packages/app-elements/src/providers/TokenProvider/validateToken.test.ts
  packages/app-elements/src/providers/TokenProvider/validateToken.ts
Labels: enhancement

#882 Increase xl tailwind breakpoint
  packages/app-elements/tailwind.config.cjs
Labels: enhancement

#883 Add `preventDefault` and `stopPropagation` to the `HookedForm`
  packages/app-elements/src/ui/forms/Form/HookedForm.tsx
Labels: enhancement

#884 Update translation
  packages/app-elements/src/locales/it.ts
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/orders.tsx
Labels: enhancement

#886 Show stock location in shipment list item
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/shipments.tsx
Labels: enhancement

#887 v4.6.1
  lerna.json
  packages/app-elements/package.json
Labels: ignore-for-release

#885 Update dependencies to the latest minor
  .github/release.yaml
  package.json
  packages/app-elements/package.json
  packages/app-elements/src/helpers/resources.ts
  packages/app-elements/src/hooks/useEditTagsOverlay.tsx
  packages/app-elements/src/mocks/stubs.ts
  packages/app-elements/src/providers/CoreSdkProvider/useCoreApi.tsx
  packages/app-elements/src/ui/composite/ListItem.test.tsx
  packages/app-elements/src/ui/composite/SearchBar.test.tsx
  packages/app-elements/src/ui/forms/InputResourceGroup/utils.test.ts
  packages/app-elements/src/ui/forms/InputSpinner/InputSpinner.test.tsx
  packages/app-elements/src/ui/forms/InputToggleButton/InputToggleButton.test.tsx
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.test.tsx
  packages/docs/package.json
  packages/docs/src/stories/forms/ui/InputDate.stories.tsx
  pnpm-lock.yaml
Labels: dependencies

#890 Set `additionalInfos` in ResourceListItem > shipments to work either with stock location or shipping method
  packages/app-elements/src/ui/resources/ResourceListItem/transformers/shipments.tsx
Labels: enhancement

#889 Handle `escapeValue` for translations in ResourceOrderTimeline
  packages/app-elements/src/locales/it.ts
  packages/app-elements/src/ui/resources/ResourceOrderTimeline.tsx
Labels: bug

#892 Update requirements of page heading generated toolbar
  packages/app-elements/src/ui/atoms/PageHeading/PageHeadingToolbar.test.tsx
  packages/app-elements/src/ui/atoms/PageHeading/PageHeadingToolbar.tsx
  packages/app-elements/src/ui/composite/Dropdown/Dropdown.tsx
  packages/app-elements/src/ui/composite/Toolbar.tsx
  packages/docs/src/stories/composite/PageLayout.stories.tsx
Labels: enhancement

#893 v4.6.3
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#894 Add attachments component
  packages/app-elements/src/locales/en.ts
  packages/app-elements/src/locales/it.ts
  packages/app-elements/src/main.ts
  packages/app-elements/src/ui/resources/ResourceAttachments/ResourceAttachments.tsx
  packages/app-elements/src/ui/resources/ResourceAttachments/index.tsx
  packages/docs/src/mocks/data/orders.js
  packages/docs/src/stories/resources/ResourceAttachments.stories.tsx
Labels: enhancement

#895 v4.7.0
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#896 Enforce `Spacer` component
  packages/app-elements/src/ui/atoms/Spacer.tsx
Labels: enhancement

#897 v4.7.1
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#898 Refine UI of `ResourceMetadata` component
  packages/app-elements/src/ui/resources/ResourceMetadata/ResourceMetadata.tsx
Labels: bug

#899 Update peerDependencies to the latest major
  .ncurc.js
  packages/app-elements/package.json
Labels: bug

#900 Switch off default debug of i18n
  packages/app-elements/src/providers/I18NProvider.tsx
Labels: enhancement

#901 Read `image_url` and `name` directly from the `stock_line_item`
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.mocks.ts
  packages/app-elements/src/ui/resources/ResourceLineItems/ResourceLineItems.tsx
Labels: bug

#902 Ignore hidden filters options in field label count
  packages/app-elements/src/ui/resources/useResourceFilters/FieldOptions.tsx
Labels: bug
