Repository commercelayer/app-elements, pull requests merged in 2025-04, with the labels that each got.

#922 Add translations for customer anonymization
  packages/app-elements/src/locales/en.ts
  packages/app-elements/src/locales/it.ts
Labels: enhancement

#923 v5.1.6
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#924 Enforce word break in `PageHeading` title
  packages/app-elements/src/ui/atoms/PageHeading/PageHeading.tsx
  packages/app-elements/src/ui/composite/__snapshots__/PageLayout.test.tsx.snap
  packages/app-elements/src/ui/composite/__snapshots__/PageSkeleton.test.tsx.snap
Labels: bug

#925 v5.1.7
  lerna.json
  packages/app-elements/package.json
  packages/docs/package.json
Labels: ignore-for-release

#926 Avoid showing broken images when notFound (`Avatar`)
  packages/app-elements/src/ui/atoms/Avatar.tsx
  packages/docs/src/stories/atoms/Avatar.stories.tsx
Labels: enhancement
